name: Deploy Android

on:
  push:
    branches: [ master ]

jobs:
  build_apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - name: Install dependencies
      run: flutter pub get
    - name: Tests
      run: flutter test
    - run: flutter build apk --debug
    - name: Upload APK
      uses: actions/upload-artifact@master
      with:
        name: apk-build
        path: build/app/outputs/apk/debug

  beta_apk:
      name: Upload Android Beta to Firebase App Distribution
      needs: [build_apk]
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
         name: apk-build
      - name: Upload APK
        uses: wzieba/Firebase-Distribution-Github-Action@v1.0.0
        with:
         appId: ${{secrets.FIREBASE_ANDROID_APPID}}
         token: ${{secrets.FIREBASE_TOKEN}}
         groups: time
         file: app-debug.apk
